# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-06 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedFile',
            fields=[
                ('md5', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('is_normalized', models.BooleanField()),
            ],
        ),
    ]
