# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swegram_main', '0002_delete_annotatedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedText',
            fields=[
                ('md5_checksum', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('normalized', models.BooleanField()),
            ],
        ),
    ]
